FROM gradle:7.4.1-jdk11

ENV DIR=simulator 

WORKDIR /life-simulation/${DIR}

COPY ${DIR}/. ./

COPY .env ../

RUN gradle --no-daemon installDist

CMD [ "build/install/simulator/bin/simulator-server" ]