version: '3.3'

services:
  
  mongo:
    image: mongo
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo
    restart: always
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - life-simulator
  
  server:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - life-simulator
    depends_on:
      - mongo
      - simulator
  
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.client
    restart: always
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      - server
  
  simulator:
    build:
      context: .
      dockerfile: simulator/Dockerfile.simulator
    restart: always
    ports:
      - "${SIMULATOR_PORT}:${SIMULATOR_PORT}"
  
networks:
  life-simulator:
    driver: brigde
