version: '3.3'

services:
  
  mongo:
    image: mongo
    restart: always
    ports:
      - "${MONGODB_PORT}:27017"
  
  server:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mongo
  
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.client
    restart: always
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
  
  simulator:
    build:
      context: .
      dockerfile: simulator/Dockerfile.simulator
    restart: always
    ports:
      - "${SIMULATOR_PORT}:${SIMULATOR_PORT}"
