version: '3.3'

services:
  
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_USERNAME}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
  
  server:
    build: server/.
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
  
  client:
    build: client/.
    restart: always
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
  
  simulator:
    build: simulator/.
    restart: always
    ports:
      - "${SIMULATOR_PORT}:${SIMULATOR_PORT}"