FROM node:12-slim

ENV DIR=server

WORKDIR /life-simu/${DIR}

COPY $DIR/package*.json ./

RUN npm install

ENV PROTOS_DIR=protos

COPY ${PROTOS_DIR} ../${PROTOS_DIR}/

COPY ${DIR}/build-proto.sh .

RUN npm run build-proto-sh

COPY ${DIR}/. ./

COPY .env ../

EXPOSE $SERVER_PORT

CMD ["npm", "start"]